name: Run Tests

on:
  push:
    branches:
      - ui_tests
  pull_request:
    branches:
      - ui_tests

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get install google-chrome-stable

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest --browser=chrome