name: Run Tests

on:
  push:
    branches:
      - ui_tests
  pull_request:
    branches:
      - ui_tests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Firefox and GeckoDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox
          wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
          tar -xvzf geckodriver-v0.33.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/

      - name: Install dependencies for Firefox
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libdbus-glib-1-dev libxtst6 libxrandr2 libx11-xcb1 libxcb1 libnss3 libcups2 libxcomposite1 libxcursor1 libxdamage1 libxfixes3 libxi6 libpango-1.0-0 libasound2
      - name: Run tests
        run: |
          pytest
