name: Run Tests

on:
  push:
    branches:
      - ui_tests
  pull_request:
    branches:
      - ui_tests

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: selenium/standalone-firefox:latest
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python and dependencies
        run: |
          apt-get update
          apt-get install -y python3 python3-pip python3-venv

      - name: Create virtual environment
        run: |
          python3 -m venv venv

      - name: Activate virtual environment and upgrade pip
        run: |
          . venv/bin/activate
          pip install --upgrade pip

      - name: Install dependencies
        run: |
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Download GeckoDriver
        run: |
          curl -L https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz -o geckodriver.tar.gz
          tar -xzf geckodriver.tar.gz
          chmod +x geckodriver
          mv geckodriver /usr/local/bin/
      - name: Run tests
        run: |
          . venv/bin/activate
          pytest